### ISSUE TITLE
Using a battery for Motobuttons 

### ISSUE THREAD

**Issue by pmfrey** [joncox123/MotoButtons#11]
Hi would you give some advice on what type of battery you would use if you wanted motobuttons to run without the USB connections. It would make it easier to swap between different bikes. Thanks. Peter

**Comment by joncox123** [comment]
The microcontroller actually supports a battery, I believe it has a lithium ion controller built in. You would want to solder a small 3.7V lithium polymer battery to the BAT +/- pads.  Please read the Seeed docs for the microcontroller for more info.
