### ISSUE TITLE
I tried  it.

### ISSUE THREAD

**Issue by harupipapaZZZ** [joncox123/MotoButtons#12]
I tried  it.

I tried changing the DMD code.

The original is

const uint8_t DMD_KEY_CENTER = HID_KEY_ENTER;
const uint8_t DMD_KEY_A = HID_KEY_F5;
const uint8_t DMD_KEY_B = HID_KEY_F6;
const uint8_t DMD_KEY_VIRTUAL = HID_KEY_F7;

but,

CENTER = HID_KEY_ENTER;
A = HID_KEY_F6
B = HID_KEY_ESCAPE;
VIRTUAL = HID_KEY_D;

Changed to
In MAP mode
A button = shortpress: zoom in (Longpress:hotomap)
B button=shortpress: zoom Out(Longpress:displayLock)
Center button = shortpress: Enter(Longpress:menu select◀▶)
It has become easier to use.

It would be useful to have a button to play music while driving and a way to specify the next song, previous song, volume up, and volume down.

But I couldn't find the code to change it.
If anyone knows please let me know.

**Comment by joncox123** [comment]
I think the solution is to add a media mode specifically for controlling the media functions in the phone, such as play track, next track, etc. This is on the to do list. I've been quite busy at work the past couple of months, but I should have some time soon.

**Comment by harupipapaZZZ** [comment]
It is a very good project and I am looking forward to it.
