### ISSUE TITLE
Suggestions for additional functions

### ISSUE THREAD

**Issue by harupipapaZZZ** [joncox123/MotoButtons#13]
1) Display current mode
It is difficult to see the current mode when using the system.
It would be good if it could be indicated by a color change in the color LED or by the number of times the LED blinks during certain operations.

2) Use a different LED from the one attached to the button.
And change to a single LED.

3)Mode change operation with a single finger
Simultaneous pressing of two buttons cannot be done with one finger.
Therefore, it is easier to operate if mode can be changed with a specific action.

4) The current joystick is small and very convenient to put a waterproof cap on it.
Since I cannot find normal tact switches with waterproof caps on the market,
Use this joystick (with waterproof cap) and use it instead of a button.
The small size allows for a smaller case.

For example
Joystick A (center & up/down/left/right)
Joystick B (center & up/down/left/right)
This allows 10 buttons to be operated.

The maximum number of buttons supported by DMD is 8, but actually there are other code assignments than F 5, F 6, and F7, so only the name should be DMD2 CTL 8K and it will work!
If you do this I am available for consultation.

**Comment by harupipapaZZZ** [comment]
Additional Requests

Current Seeed Studio XIAO nRF52840
from
Seeed Studio XIAO to ESP32C3

It supports Bluetooth 5 LE and WIFI and is less expensive.

**Comment by razorbac91** [comment]
> Additional Requests
> 
> Current Seeed Studio XIAO nRF52840 from Seeed Studio XIAO to ESP32C3
> 
> It supports Bluetooth 5 LE and WIFI and is less expensive.

I tried last week to program a super simple blekeyboard with an ESP32C3 super mini, but I can't make it working. It connect fine but doesn't output anything, same code on a D1 esp32, works flawless

**Comment by joncox123** [comment]
media (music) mode has been added as the forth mode

**Comment by harupipapaZZZ** [comment]
Confirmed thank you
