### ISSUE TITLE
USB-c port

### ISSUE THREAD

**Issue by pmfrey** [joncox123/MotoButtons#2]
Am I missing it or is there a link to find a usb-c port if you want to use that?

**Comment by joncox123** [comment]
Sorry, do you mean a USB-C cable?

**Comment by pmfrey** [comment]
I don't think so, but maybe I misunderstood the build instructions. I meant usb-c female port to build into black box, but looking at the image again I realize the usb-c female port is built into the seed controller.  sorry that wasn't clear to me. I'm not really an electronics person, but have a competent friend who's going to help me build this. anyway thanks.  I also put a comment on the dmd2 fb page but I'll delete it. I just didn't see a 'usb-c' anything o the parts list so was curious but didn't pay attention to the photo.

**Comment by joncox123** [comment]
No, you don't need to buy a USB-C port, that is already soldered onto the microcontroller.

**Comment by joncox123** [comment]
Issue resolved
