### ISSUE TITLE
Seeeduino XIAO ESP32C3

### ISSUE THREAD

**Issue by harupipapaZZZ** [joncox123/MotoButtons#4]
Seeeduino XIAO ESP32C3
This is a. WI-FI and blutooth 5.0 are available.
WI-FI is available for OTA updates during development.

Half the price of the Seeed Studio XIAO nRF52840

I haven't used it yet, but there seem to be some caveats.
https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/

I'm not familiar with programming, but if I use this, do I need to change the wiring or code?

**Comment by joncox123** [comment]
Yes, the code will be completely different and will need to be rewritten. But that's a good find, I'm not sure why I didn't see that model. I might order one and test it out.
