### ISSUE TITLE
Need help it is not working

### ISSUE THREAD

**Issue by Joergen57** [joncox123/MotoButtons#5]
Hi, I finished the build installed the software and code and it seems all ok, but the controler does nothing.
I disconnect the controller from power and reconnect more then ons. No LED flashing, I checked LED function and wireing, it is ok.
I am totally new regarding programing and Arduino. I hope I followed the instructions correctly. 
From screenshot  I think it looks ok.

![Screenshot (34)](https://github.com/joncox123/MotoButtons/assets/148914179/b1bc4261-b269-40a2-af09-c8a9c20e2907)

There is no Bluetooth to see.  So what would be the next step to find the problem?

**Comment by Joergen57** [comment]
HI, I have no idea what happen, I went through the tools menu and clicked monitor and suddenly the LEDs starts flashing. I can connect now via BT and controller is working. Big ? what happend.
So can be closed for now.

**Comment by joncox123** [comment]
It looks like it programmed OK. Check with a multimeter that you are getting 5 V between the 5V and GND pins on the microcontroller. I think you must have a power or wiring issue. Check that you didn't reverse the LED connection, those have a polarity.

**Comment by joncox123** [comment]
oh, I see it's fixed. Good!

**Comment by Joergen57** [comment]
OK, I could limit the problem a bit. It is not working with a power bank connected via USB-C. I tried two different ones. It works only with a USB-Cable connected to a PC. May be an additional signal is needed what a power bank can not supply. The power consumption is lower then 0.00 A.

Another problem found, it works only at the PC where Arduino IDE is runing, not at another PC USB connector.
When I close Arduino IDE at the working PC it still works, but when I reconnect it does not.
Starting Arduino IDE again then it is working agin.
Very strange?
May be I need to attached 5V via extra USB-cable wired to PCB.

**Comment by Joergen57** [comment]
So it is not a power bank problem.

**Comment by Joergen57** [comment]
So, direct attached 5V does not change anything, still not working. I checked 5V on the Board, it is available, by external power and/or USB-C power, same for the 3.3V it is there at both.

**Comment by joncox123** [comment]
I will run a few tests today and let you know what I find. But it seems like it might be a wiring issue. Make sure that nothing can short out. Also, check wiring and LED polarity.

**Comment by joncox123** [comment]
I am seeing a similar thing. It looks like a programming issue where it does not retain the program after disconnection from the PC. Let me research how to resolve this. I know the Arduino is suppose to retain the program since it is written to flash memory.

**Comment by joncox123** [comment]
Ok, I think I know what the problem may be. The code is probably waiting for a USB serial port connection when it starts up. Thus, I probably need to modify the source code so that it does not do that. I will test that out in about an hour and upload new code if it fixes it.

**Comment by joncox123** [comment]
Hi, I fixed the problem. The code was indeed waiting for the connection of a USB serial port. That is why it was not working when not attached to a PC. I tested it from a USB charger, and it is working OK. I will close this for now, but open a new issue if you have another problem. Thank you

**Comment by joncox123** [comment]
Also, please upload the latest source code version, v1.1.1, using the Arduino IDE. After that, the problem should not reoccur.

**Comment by Joergen57** [comment]
Thanks for the quick reaction and help to fix it.
The new code looks a bit strange and it includes my Mail address? Please delete this!

**Comment by joncox123** [comment]
No, it does not have your mail address. Where are you seeing this? Are you looking at the correct repository?

**Comment by Joergen57** [comment]
![Screenshot (36)](https://github.com/joncox123/MotoButtons/assets/148914179/1aeca6cf-52ff-4403-ac19-2153685c0495)

**Comment by Joergen57** [comment]
something went wrong with the download I gues

**Comment by joncox123** [comment]
I think you downloaded the entire web page instead of just the code. Try downloading only the code or copy and paste it into the IDE.

**Comment by Joergen57** [comment]
Seems a mistake on my site, sorry. (absolute beginner)  ;-)
So looks good, runs now with power bank and a blue LED is blinking at (i guess) boot.

**Comment by Joergen57** [comment]
Where can I make suggestions, here under issues?

**Comment by joncox123** [comment]
Yes, open a new issue for a suggestion.
