### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ConTS10** [joncox123/MotoButtons#7]
I like this project very much, but I hate the smudgy look of the sealing method. Would it be an idea to stick the joystick through a round hole from the inside of the box, and press it, with the rubber boot in between, against the outer wall by a constructed bridge from the inside? I might think up a 3d-printed case over the winter that does exactly this. The result is also that the stick does not stick out that much.

**Comment by joncox123** [comment]
That won't work, but it's possible to use your finger to smooth the silicone sealant better. The project is mainly about price over appearance. For a nice appearance, there are many commercial options for $250 to $300.
