### ISSUE TITLE
Change button parts

### ISSUE THREAD

**Issue by harupipapaZZZ** [joncox123/MotoButtons#9]
The current button is a button switch with LED, can I change it to a normal button (tact switch without LED)?
This is because the LED is not visible when you press the button and is cheaper to manufacture than using a button with an LED.

Can I use two regular LEDs and connect "LED_BUTTON_A", "LED_BUTTON_B" and "GND"?

Do I need to change the source code?

I am wondering if it is possible to use a thin tact switch instead of the specified waterproof LED button.
The main body BOX can also be made thinner.
(Isn't one LED actually enough?)

**Comment by Joergen57** [comment]
I belive this is possible and no need two change the code.

**Comment by harupipapaZZZ** [comment]
thank you

There was a long wait for the parts I ordered from MONSTER due to export procedures. It will finally arrive tomorrow.

When the parts arrive, I will try to make a temporary connection to check the operation.

**Comment by Joergen57** [comment]
My first version is working. I recommend reading all issues.
What will be the usage for your MotoButtons?
I will use it for MyRoute-App.

**Comment by harupipapaZZZ** [comment]
Mainly DMD2, but
I also want to use ROADBOOK and music with R1200GS.
I look forward to adding more modes.

The R1200GS has a large left switch area, so I would like to make it thinner if possible.

P.S.
Do I need to press the chip reset button when updating? Is it not enough to just use a button switch with an LED?
I would like to embed it if possible to make it waterproof.

We are considering creating the case using a 3D printer.
If I come up with a good design, I'll share it.

**Comment by harupipapaZZZ** [comment]
It is still a prototype,
Smaller with tact buttons and joystick

There are no waterproof caps for tact buttons on the market, so I made a mold out of silicon.

https://github.com/joncox123/MotoButtons/assets/129697360/59f4436a-33fb-49c7-8fb6-362684c84435

**Comment by Joergen57** [comment]
Cool, I like the tiny buttons. What buttons are this exactly? And how did you do the silicon covers?

**Comment by harupipapaZZZ** [comment]
ALPS tactswitch "SKRGAED010"

Based on this, we made a 3D drawing covering the entire switch and
Print it with a 3D printer (UV curing for precision)

Put the finished product in a mold to create a silicon mold (top and bottom)
Then pour the silicon into the mold and shape it.
It takes a tremendous amount of time and effort.

This is a leftover from a previous project.





<img width="415" alt="スクリーンショット 2023-11-19 1 45 52" src="https://github.com/joncox123/MotoButtons/assets/129697360/c3d624c8-f6a8-4656-b95b-dc14ad3282e5">

**Comment by harupipapaZZZ** [comment]
<img width="679" alt="スクリーンショット 2023-11-19 1 52 55" src="https://github.com/joncox123/MotoButtons/assets/129697360/da55d20a-3b9f-4a72-abee-247a5ab4696f">

Since there are two LEDs, they take up a lot of space.
It would be nice to have only one LED because it would make the design more compact.

Currently designing a vertically aligned body
![IMG_7888](https://github.com/joncox123/MotoButtons/assets/129697360/2b8fe889-222e-4765-962a-503e3fb167fa)

**Comment by Joergen57** [comment]
I am not sure what the second LED is for. I know the LED on Zoom + indicates the 3 modes. Maybe Jon can answer this.

**Comment by joncox123** [comment]
Hi, I've been quite busy at work, but I plan to revisit development soon. I agree, the LED buttons are a pain because you can't see the light when you press the switch. Since the LED is just a separate set of terminals, you can use different buttons and easily wire up a separate LED somewhere else.

**Comment by lostinalps** [comment]
> It is still a prototype, Smaller with tact buttons and joystick
> 
> There are no waterproof caps for tact buttons on the market, so I made a mold out of silicon.
> 
>  large.mov

Where did you find the joystick? Is it waterproof?
